### ISSUE TITLE
Would it be possible to use png instead of svg as the source?

### ISSUE THREAD

**Issue by saeid-elio** [aeirola/react-native-svg-app-icon#105]

**Comment by aeirola** [comment]
Thanks for the suggestion. I suppose it could be possible for some of the icon formats as the underlying sharp library is quite flexible. But wouldn't be possible to produce all desired outcomes at high quality without a vector input. So this isn't something I'd be willing to add.

For raster icons there are already built in solutions in [Expo](https://docs.expo.dev/develop/user-interface/splash-screen-and-app-icon/), as well as the [app-icon](https://github.com/dwmkerr/app-icon) tool

**Comment by saeid-elio** [comment]
Thanks. I went with https://www.npmjs.com/package/app-icon as it allows generating all icons from a single png image.
