### ISSUE TITLE
Use with plain cordova?

### ISSUE THREAD

**Issue by phatpaul** [aeirola/react-native-svg-app-icon#58]
I would like to use it with a Cordova project (not react-native).

I was able to use it to generate the Android icons since it just spit them out in a folder /android (it created the folder).
But iOS gives an error that the /ios folder is missing.  I added an empty /ios folder, then it says: 
(node:1880) UnhandledPromiseRejectionWarning: Error: No Images.xcassets found under ios/ subdirectories

How can I get it to create the iOS images?  Is there some other tool or fork for svg -> icons for cordova.

**Comment by aeirola** [comment]
Cordova seems to be using quite a different kind of configuration and structure for the app icons (https://cordova.apache.org/docs/en/10.x/config_ref/images.html). As `react-native-svg-app-icon` is only meant to be used with react native, I don't think there is much I can do to support cordova here.

As I'm not that up to date with the cordova development, I don't really have anything specific tool to recommend. https://github.com/ionic-team/cordova-res seems to be well maintained but doesn't seem to support SVGs though. Maybe you can use a separate tool to generate a PNG from your SVG file, and then run the result through cordova-res?
